spring:  h2:    console:      enabled: true      path: /h2-console
  datasource:    url: jdbc:h2:mem:testdb
    username: sa
    password:     driver-class-name: org.h2.Driver  application:    name: CustomerRecordsApplication    logging:  level:    org.springframework.cloud.task: DEBUG

csvFileDirectory.path: "C:\\Records\\Input"
outputDirectory.path: "C:\\Records\\Output"
xmlFileDirectory.path: "C:\\Records\\Input"cron.expression: "0 0 23 29 1/1 ? *"